FROM nginx:latest

RUN apt-get update && apt-get install -y \
    certbot \
    python3-certbot-nginx \
    cron \
    && apt-get clean

RUN mkdir -p /etc/letsencrypt

RUN echo "0 0 1 */5 * certbot renew --quiet && nginx -s reload" > /etc/cron.d/certbot-renew

RUN chmod 0644 /etc/cron.d/certbot-renew

RUN service cron start

# CMD ["nginx", "-g", "daemon off;"]