services:
  app:
    image: bitnami/laravel:latest
    restart: unless-stopped
    container_name: app
    depends_on:
      - db
      - web
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=laravel
      - DB_PASSWORD=g13rv5JhtJ
    volumes:
      - ./www:/app
    networks:
      - laravel_network

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - laravel_network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: g13rv5JhtJ
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  dbdata:


networks:
  laravel_network:
